schema_version = "1.0.0"

id = "csv_importer"
version = "0.1.3"
name = "CSV Importer"
tagline = "import csv data to meshes in Blender"
maintainer = "Jan-Hendrik Müller<jan-hendrik.mueller@uni-goettingen.de>"
type = "add-on"
website = "https://github.com/kolibril13/blender_csv_import"
platforms = [
	"windows-x64",
	"linux-x64",
	"macos-arm64",
	"macos-x64",
]
tags = [
	"Geometry Nodes",
	"Import-Export"
]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later"
]
copyright =[
	"2024 Jan-Hendrik Müller",
]
wheels = [
	"./wheels/polars-1.17.1-cp39-abi3-macosx_10_12_x86_64.whl",
	"./wheels/polars-1.17.1-cp39-abi3-macosx_11_0_arm64.whl",
	"./wheels/polars-1.17.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/polars-1.17.1-cp39-abi3-win_amd64.whl",
]



[permissions]
files = "Importing data files from disk"

# make sure only __init__.py , polars_mesh.py and wheels/ are included.

[build]
paths_exclude_pattern = [
  "build.py",                     # Exclude build.py
  "data_california_housing.csv",  # Exclude CSV files
  "data_gemeran_cities.csv",      # Exclude CSV files
  "fake_polar_ice_data.csv",      # Exclude CSV files
  "image-1.png",            # Exclude images
  "image.png",              # Exclude images
  "LICENSE",                # Exclude LICENSE
  "README.md",              # Exclude README.md
  ".gitignore",             # Exclude gitignore
  ".DS_Store",              # Exclude DS_Store
  "*.zip",                  # Exclude *.zip
  "*generate_data/*",       # Exclude /generate_data folder
  "*__pycache__/",       # Exclude /__pycache__ folder
  ".venv/",                 # Exclude .venv folder
  ".git/",                  # Exclude .git folder
]