name: Run Tests

on: 
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: ["4.2", "4.3"]
              os: [macos-14, windows-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v4


            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v4
              with:
                version: "latest"
            
            - name: Install
              run: |
                uv sync  --all-extras --dev
                uv pip install bpy==${{ matrix.version }}
            
            - name: Run tests
              run: |
                uv run -m pytest -vv --cov=databpy --cov-report=xml
    
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
            
            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
    
